using System;
using System.Diagnostics;
using System.IO;
using System.Windows.Forms;

class Launcher {
    [STAThread]
    static void Main() {
        // Name of the JAR file generated by Maven
        string jarName = "VeneClicker-1.0-SNAPSHOT.jar";
        string currentDir = AppDomain.CurrentDomain.BaseDirectory;
        string jarPath = Path.Combine(currentDir, jarName);

        if (!File.Exists(jarPath)) {
            MessageBox.Show("Could not find " + jarName + "\nMake sure it is in the same folder as this executable.", "VeneClicker Launcher Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            return;
        }

        ProcessStartInfo startInfo = new ProcessStartInfo();
        startInfo.FileName = "javaw";
        startInfo.Arguments = "-jar \"" + jarPath + "\"";
        startInfo.UseShellExecute = false;

        try {
            Process.Start(startInfo);
        } catch (Exception e) {
             MessageBox.Show("Could not start Java.\nError: " + e.Message, "VeneClicker Launcher Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
    }
}
